########################################################################################################################
# Example:
########################################################################################################################

#
# [[dependency]]                           # Toml way to define array of objects.
# python = "../../_build/target-deps/python"  # Path to python used to install. Absolute or relative to this config.
# packages = ["numpy"]                     # Array of packages to install, they all will be passed directly to pip.
# target = "../../_build/target-deps/numpy"   # Folder to install into.   Absolute or relative to this config.
# platforms = ["windows-x86_64"]           # Platform(s) to filter, default is ["*"].
# download_only = true                     # Do pip download instead of install, gets a whl file that can be installed later.
#

# Another sample
# [[dependency]]
# python = "../../_build/target-deps/python"
# packages = [
#     "toml==0.10.1",
# ]
# target = "../../_build/target-deps/pip_prebundle"
# platforms = ["*"]
# download_only = false
# append_to_install_folder = true
# python_include_dir = true
# subprocess_path = ["${root}/_build/host-deps/msvc/MSBuild/Current/Bin", "${root}/_build/host-deps/msvc/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64", "${root}/_build/host-deps/msvc/VC/Auxiliary/Build", "${root}/_build/host-deps/winsdk/bin/x64"]
# msvc_path = "${root}/_build/host-deps/msvc/VC/Tools/MSVC/14.29.30133"
# win_sdk_path = "${root}/_build/host-deps/winsdk"

[[dependency]]
python = "../../_build/target-deps/python"
packages = [
    "watchdog==0.10.4",             # SWIPAT filed under: http://nvbugs/3194408
    "pydantic==2.9.0",
    "requests==2.31.0",
    "sseclient-py==1.8.0",
    "packaging",
    "pydot",
    "jinja2",
    "watchdog",
    "dfm-client",
    "async-timeout==4.0.3",
    "numpy",
    "skyfield"
]
target = "../../_build/target-deps/pip_prebundle" # This folder will be linked into 'example.mixed_ext' extension (see premake file)
platforms = ["*"]
download_only = false
append_to_install_folder = true
gather_licenses_path = "../../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
extra_args = [
    # "--extra-index-url", "https://urm.nvidia.com/artifactory/api/pypi/ct-omniverse-mirror-pypi/simple/",
    "--find-links", "./deps/wheels",
    # "--extra-index-url", "https://urm.nvidia.com/artifactory/api/pypi/nv-shared-pypi/simple/",    # Internal index for dfm-client
    ]