[package]
# Semantic Versioning is used: https://semver.org/
version = "0.3.1"

# The title and description fields are primarily for displaying extension info in UI
title = "Feature Properties Window"
description = "Window to view and edit E2 Visualization Features"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Path (relative to the root) or content of changelog markdown file for UI.
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = "https://github.com/NVIDIA-Omniverse-blueprints/earth2-weather-analytics"

# One of categories for UI.
category = "setup"

# Keywords for the extension
keywords = ["kit", "setup"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.ui" = {}
"omni.kit.window.popup_dialog" = {}
"omni.earth_2_command_center.app.core" = {}
"omni.earth_2_command_center.app.shading" = {}

# Main python module this extension provides
[[python.module]]
name = "omni.earth_2_command_center.app.window.feature_properties"

[settings]
